### ISSUE TITLE
Form picker not working in content

### ISSUE THREAD

**Issue by leon-dp** [rhythmagency/formulate#111]
I'm having an issue using the Formulate plugin. Installing the plugin and creating forms are working great. However, when I try to select a form using the form picker in [Content], nothing happens. I did notice that when the [Choose] button is clicked, the call to GetEntityChildren seems to return invalid json. The option is still shown despite the error, but clicking it does nothing. No calls, no errors. 

I tested this in Umbraco versions 7.7.7, 7.7.0, 7.6.12 and 7.4.1, using the package repository to install Formulate 1.3.5.

![form](https://user-images.githubusercontent.com/4338703/34515199-3d4185ba-f071-11e7-98c8-f06a04772239.png)

![json](https://user-images.githubusercontent.com/4338703/34515498-910027f0-f072-11e7-8780-1723c7b9c199.png)

**Comment by Nicholas-Westby** [comment]
Seems like everything is working as intended. The message "note that configured forms reside under forms" that appears in your screenshot means that you should be picking a configured form rather than a form itself. Before you can pick a configured form, you need to be sure to create it (under the form). You can read more about creating/picking forms here: http://www.formulate.rocks/simple-form

Also, the response is actually not invalid, though it is invalid JSON. This is something AngularJS does for security reasons (it rips out the first few funky characters before the receiving code ever sees it).
