### ISSUE TITLE
How to load data from third party

### ISSUE THREAD

**Issue by sheryever** [rhythmagency/formulate#113]
How i can load the dropdown list data from third party json/ws/rest.

I have a asp.net mvc application, where i have to submit the data and also need to load the some data in a dropdown from that application.

**Comment by Nicholas-Westby** [comment]
Implement the `ISupplyValueAndLabelCollection` interface. More info here: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/79633-formulate-036-just-released-data-value-list-functions

BTW, discussions are better had in the forums rather than on the issue tracker: https://our.umbraco.org/projects/backoffice-extensions/formulate/formulate-questions/
