### ISSUE TITLE
Data Value Drop Down

### ISSUE THREAD

**Issue by jaydcrowe1989** [rhythmagency/formulate#120]
Hi,

Is there a way of preventing the label of the drop down showing as the first option in the drop down list? I have quite a long label for the drop down field and I would prefer not to show it when the form is rendered on the page.

Cheers,
Jay

**Comment by Nicholas-Westby** [comment]
Not that I recall. Here are some options.

# Workaround

You can create a short label that will show up in the drop down, then use a CSS style to hide the actual label on the drop down field.

Then, you can use the rich text field to add a sort of fake label above the drop down field. Not ideal, as the label won't be able to set focus on the drop down when the label is clicked, but it should visually look pretty similar, depending on how you're laying out the fields.

# Formulate Core Solution

The AngularJS template of Formulate has the ability to set some configuration, IIRC. You could submit a pull request that allows a configuration value for how to render the drop down label (e.g., so you can exclude it from the items in the drop down). Another idea would be to specifically set a secondary label specifically to be shown inside of the drop down list, so if that interests you that could also be a PR that you submit.

# Extend Formulate

You can create a custom field type where you implement the drop down however you like. Since Formulate is extensible, this requires no modification to the core of Formulate.

# Modify AngularJS Template

Formulate comes with the source JavaScript files used to render the fields. You could modify these files and build them yourself. That would have the disadvantage that you'd have to be mindful not to clobber your changes when you upgrade Formulate.

# CSS Approach

You may be able to hide the first option in the select field. That may then hide the label. If this works, it's probably the simplest and most straightforward solution.
