### ISSUE TITLE
Allowing the cancellation of form submissions

### ISSUE THREAD

**Issue by TFAstudio** [rhythmagency/formulate#129]
When submitting a form, we are allowed to use the `FormSubmissionContext` to change or validate the form information inside a `Submitting` event.  I would like to propose a change so one can cancel the form submission by creating a boolean inside the `FormSubmissionContext` object.  I have made a first attempt at this and below is the unified diff.

```
@@ -139,13 +139,21 @@
                 UmbracoContext = context.UmbracoContext,
                 UmbracoHelper = context.UmbracoHelper,
                 SubmissionId = Guid.NewGuid(),
-                ExtraContext = new Dictionary<string, object>()
+                ExtraContext = new Dictionary<string, object>(),
+                SubmissionCancelled = false
             };
 
 
             // Invoke submitting event (gives listeners a chance to change the submission).
             Submitting?.Invoke(submissionContext);
 
+            if (submissionContext.SubmissionCancelled)
+            {
+                return new SubmissionResult()
+                {
+                    Success = false
+                };
+            }
 
             // Validate against native field validations.
             foreach (var field in form.Fields)
```

**Comment by TFAstudio** [comment]
Hmm I still can't figure out what I did wrong and now I cant seem to get the pull request happening linked to the changes I made.  Is there a URL to read the process to ensure I do this correctly?

**Comment by Nicholas-Westby** [comment]
Here is some general documentation: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Just make sure that you work against the develop branch. Typically, this would mean you would fork the repo, switch to the develop branch, create a feature branch based off of that branch (e.g., "feature/129-cancel-form-submissions"), commit, push to your fork, then send a pull request (via the GitHub interface, as mentioned in the above link).

If you've deviated from that, may cause some issues. You may need to update your fork so that you have all the latest code, and then merge the develop branch into your feature branch. This shows how to update a fork: https://help.github.com/articles/syncing-a-fork/

**Comment by TFAstudio** [comment]
I have built against the Develop branch, and it _looks_ like I've got that, but it seems to be sticking to the same changes you have made already.

**Comment by Nicholas-Westby** [comment]
FYI, the develop branch is lowercase. You are referring to it as uppercase. Maybe that's causing some issue.

You could always go with the nuclear option. That is, copy your code somewhere, delete your fork, recreate the fork, then apply the changes again, making sure to branch off of the develop branch.

**Comment by Nicholas-Westby** [comment]
IIRC, the pull request for this got merged in. Closing.
