### ISSUE TITLE
Feature request: multi-page forms

### ISSUE THREAD

**Issue by jamiehowarth0** [rhythmagency/formulate#165]
As it says on the tin!

**Comment by Nicholas-Westby** [comment]
Poking around with this now for fun, though I don't expect to have something entirely working soon. Just an FYI in case anybody else also happened to be poking around with this.

**Comment by Nicholas-Westby** [comment]
Was easier than I thought. I got a prototype working on the develop branch (haven't tested submissions yet, and probably want to fine-tune the validation management, but it seems to work in general).

Here's the back office:

![backoffice](https://user-images.githubusercontent.com/5933222/74124079-ed2b6880-4b85-11ea-91cf-4d563d38425d.png)

And here's the frontend (there are no styles, so that's why you don't see rows/columns):

![frontend](https://user-images.githubusercontent.com/5933222/74124086-f3b9e000-4b85-11ea-9e4f-bb0a8c3d4bb1.png)

The next and previous buttons work.

This is the commit of the work so far: https://github.com/rhythmagency/formulate/commit/d278605c9c28be94ad223df93bb1e4953477a62a

**Comment by FuelAgency** [comment]
Hey, nice progress!
People are going to love this.

**Comment by jamiehowarth0** [comment]
@Nicholas-Westby great work! I'll check this out!

**Comment by Nicholas-Westby** [comment]
I improved the validation so it happens on each step transition: https://github.com/rhythmagency/formulate/commit/7f0da161833fe1d79788d358e26496f265a3697e

This is now complete. It will be part of the next Formulate v3 release.

**Comment by Nicholas-Westby** [comment]
This is in the latest release of Formulate (version 3.2.1).

**Comment by jamiehowarth0** [comment]
@Nicholas-Westby great work! #h5yr
