### ISSUE TITLE
No option to modify message after submit button

### ISSUE THREAD

**Issue by harshwardhandangra** [rhythmagency/formulate#170]
No option to modify message after submit button

**Comment by Nicholas-Westby** [comment]
Assuming you are talking about the confirmation message that appears once a form has been submitted, this is an implementation detail that is outside of the scope of Formulate. The Formulate documentation shows an example of what you can show after the form is submitted, but that is really something that's up to you to implement.

This is because there are many ways of going about this (e.g., macros, widgets, grid, static, based on a property, dynamic based on context, a redirect, and so on).

**Comment by harshwardhandangra** [comment]
@Nicholas-Westby Please check the below screenshot. but its not sending data and after click submit no place where i can put custom message

http://prntscr.com/sejwey

https://prnt.sc/sel4os

http://prntscr.com/sel63r

**Comment by Nicholas-Westby** [comment]
As I said, this is a concern that is outside of the scope of Formulate. You can make a dynamic success message if you program one. If you don't program one, it won't be dynamic.

This page shows an example of how you can create a success message (assuming you are using the plain JavaScript template): http://www.formulate.rocks/plain-javascript/render-form

Here is the snippet in particular:

```
// On form submit, remove the form and display a success message. You can do what you like here
// (e.g., show a hidden element).
wrapper.addEventListener("formulate form: submit: success", function (e) {
	let form = e.target;
	form.parentNode.replaceChild(document.createTextNode("Form submitted!"), form);
	if (validationListElement) {
		validationListElement.parentNode.removeChild(validationListElement);
	}
	validationListElement = null;
});
```

Note the code comment that says "you can do what you like here".
