### ISSUE TITLE
Google Analyics tracking of successful submissions?

### ISSUE THREAD

**Issue by TFAstudio** [rhythmagency/formulate#180]
Hey Nicholas and all,

I'm curious to know if there is a built-in, documented way to send Google Analytics or GTM an event when someone completes a form submission.

I see there's a handler to Send Data - could that be used?

I'm currently using formulate for Umbraco v8.
Any leads would be greatly appreciated.

Thanks,
AE

**Comment by Nicholas-Westby** [comment]
That's usually done client side (i.e., you wouldn't want to use a send data handler, since that is server side). I believe GA or GTM offers a way to subscribe to form submit events on the client side. Though, form submits don't indicate a successful form submission. If you like, you can listen for the `formulate form: submit: success` JavaScript event and then perform a GTM data layer push. Here's an example of that event, though not in an analytics context: https://www.formulate.rocks/plain-javascript/render-form

Data layer pushes usually look something like this:

```javascript
dataLayer.push({/* Some properties here. */});
```

If you have additional questions, the forum would be a better place to ask them: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

Closing this ticket now.
