### ISSUE TITLE
Form persistence in Umbraco database

### ISSUE THREAD

**Issue by liamfiddler** [rhythmagency/formulate#191]
👋 Hello!

I'm using Formulate in a scalable setup where there are multiple servers. Unfortunately because Formulate persists forms as JSON in the filesystem when you edit/configure a form on one server the others do not have access to these files and receive the updates.

I see on the [extensibility page](https://www.formulate.rocks/extensibility) it says "You could, for example, create a persistence layer that stores to SQL Server".

As all the servers can access the same database it sounds like persisting the form config to the database would be a good solution.

1. Does this sound like the right approach?
2. Are there any code examples of updating the persistence layer I could use as a basis?

Thanks for the great work on this tool!

**Comment by Nicholas-Westby** [comment]
Hello,

FYI, a better place to ask questions like this would be in the forum: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

Before I get into details, you might also consider using something like DFS to sync the file system between each server: https://en.wikipedia.org/wiki/Distributed_File_System_(Microsoft)#DFS_replication

One gotcha to keep in mind there is Formulate has some internal caches, so it could be a moment before each server reflects the changes from the primary server that made the change.

There is no documentation, but since it is open source I can point you to a few examples. You'll probably want to start here: https://github.com/rhythmagency/formulate/tree/v3/master/src/formulate.app/Persistence

This is what manages persistence currently. It shows both the interfaces and the implementations (that currently store entities to the file system as JSON).

DefaultEntityPersistence is probably a good second place to look: https://github.com/rhythmagency/formulate/blob/v3/master/src/formulate.app/Persistence/Internal/DefaultEntityPersistence.cs

I can't remember if that implementation needs to change or if you just need to change the other implementations that it makes use of (e.g., `IFormPersistence`, which by default is `JsonFormPersistence`).

Finally, you'll want to look at the composer that registers the implementations for the interfaces: https://github.com/rhythmagency/formulate/blob/5e0a722ca5854597999f8d38da91fd941c26ec10/src/formulate.app/Composers/CompositionRegistryUserComposer.cs

You'll want to register your own implementations instead.

I haven't tried replacing the implementation, but it should work in theory. If you need assistance with ideas, please post in the forum. If you run across bugs or changes you need, the issue tracker here is the better place to post.

BTW, if you'd like to submit a pull request, this might be something that'd make sense to include with the core of Formulate so everybody can opt into using it. If so, there would need to be some configuration that sets which of the persistence implementations to use (i.e., JSON file system or in the database). Creating an Umbraco package or a NuGet package would be another option to make the functionality available to others.

Good luck!

**Comment by liamfiddler** [comment]
Thanks for the detailed and super quick response! And sorry for not thinking of using the forum for this query.

DFS is a great idea that I hadn't considered, I'll explore that option first... But if I do end up writing a new persistence layer I'll try to make it generic/reusable and submit a PR 👍
