### ISSUE TITLE
Support CAPTCHA

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/formulate#2]
This will help prevent bot spam.

**Comment by biapar** [comment]
+1

**Comment by MuirisOG** [comment]
+1

**Comment by LeaTark** [comment]
This is probably the biggest problem for us.  Our users are demanding CAPTCHA. 
Any CAPTCHA would be great.  No CAPTCHA reCAPTCHA would be fantastic.

**Comment by FuelAgency** [comment]
Perhaps there is a hidden field / honeypot approach that could be recommended as a basic interim measure? A per-form default honeypot Enable/Disable setting could help even novice users to eliminate at least some of their spam. #mytwocents

ps. Really liking the updates and increased functionality that's come to formulate! Struggling a little with lack of validation on some settings/mandatory fields, which result in forms not rendering.

**Comment by Nicholas-Westby** [comment]
Interestingly, I haven't noticed any bot spam yet in the Formulate forms I've implemented. Perhaps because Formulate uses AJAX for submissions and most bots expect full postbacks? Not really sure. I would be curious to know if others are actually getting any bot spam.

Of course, CAPTCHA is a useful feature and it should definitely be implemented; it would just help to prioritize knowing what people are seeing right now.

@FuelAgency I'm curious to know which issues you've run into regarding forms not rendering. Please feel free to submit a separate ticket with details.

**Comment by FuelAgency** [comment]
We had problems with YSOD with unhelpful errors about missing datatypes. It turned out to be related to Layouts. One Layout had a Row with no fields in it. Removing the Row restored functionality. 
For other forms which were failing silently, we simple had to re-pick the Form for the Layout and things began working again.
It was a challenge because all three of our forms were failing, but for differing reasons. I've not succeeded in reproducing the issues, but was trying a LOT of ways to get it back, like filling out empty Field Alias and Field Category fields in case they were related (I'm not sure they were).

**Comment by Nicholas-Westby** [comment]
FYI, a recaptcha field type has been implemented. Will release in a few days after making further enhancements.

For reference, this was the commit: https://github.com/rhythmagency/formulate/commit/2c6b8328e1aae1ebdbe690ee5469ef1003a0ba8e

**Comment by biapar** [comment]
Very Good!

**Comment by Nicholas-Westby** [comment]
FYI, the new recaptcha field was just released a few days ago.
