### ISSUE TITLE
[Question] Umbraco 9

### ISSUE THREAD

**Issue by icavalheiro** [rhythmagency/formulate#201]
Hi,

Is there any plans to support Umbraco 9 and .net 5 / .net 6 ?

**Comment by Nicholas-Westby** [comment]
It is very likely, yes. Just a matter of when time can be made. If any community members want to help support the effort, that would be appreciated, and it would help expedite the process.

**Comment by huwred** [comment]
@Nicholas-Westby I see there is now a V4 branch of the code, Is there anything I can do to help move your project along?

**Comment by Nicholas-Westby** [comment]
@huwred Yeah, work on it has stalled out on our end (due in part to the quick pace of Umbraco releases). I recommend targeting Umbraco 10 since that is the long term support version (Umbraco 11 will have a short lifespan). If you are interested in moving it to the finish line, let me know and we can talk about a specific strategy (e.g., outlining issues, PRs, and such).

Please also submit a message here so I have your email and we can chat directly: https://www.nicholaswestby.com/contact
