### ISSUE TITLE
Umbraco v8 - Problems with Custom Responsive Form Template (Angular)

### ISSUE THREAD

**Issue by afabri73** [rhythmagency/formulate#203]
Hi Nicholas,
I installed Formulate for Umbraco v8 and I'm trying to create a Custom Responsive Angular Template to display my Form
I managed to configure the frontend to use Angular but I can't access the form fields.
Attached I send you the Formulate Site Master Template, the Custom.Render.Form Partial View and the results on page.

As you can see the page correctly displays the form data (JSON), and data are correctly passed as source of formulate-json-source object...but...the formulate-responsive-form form-data="::ctrl.data" object cannot find the fields data and generating the error that you can see in the attached image.
I think that the JSON data isn't in correct format, but I'm not sure.
Can you help me?

Thank you
Adriano

[FormulateSiteMaster.txt](https://github.com/rhythmagency/formulate/files/7426605/FormulateSiteMaster.txt)
[Custom.Render.Form.txt](https://github.com/rhythmagency/formulate/files/7426610/Custom.Render.Form.txt)
![Immagine 2021-10-27 142246](https://user-images.githubusercontent.com/6714121/139078251-755d4d2b-c40a-4c00-8b88-2e7f38298038.png)

**Comment by Nicholas-Westby** [comment]
Hi Adriano,

I'll see if I can take a look tonight/tomorrow or late next week.

In the meantime, is there some reason you're not using the plain JavaScript template? I would recommend that one for new projects.

Also, why a custom AngularJS template rather than the built-in AngularJS template?

Side note: you may get a quicker response if you use the forum, as more people have the opportunity to see your question there: https://our.umbraco.com/packages/backoffice-extensions/formulate/formulate-questions/

**Comment by afabri73** [comment]
Hi Nicholas,
thank you for the answer and I'll look forward to your look. :-)

I already use the Plain JavaScript Template for various forms but now I would to use Angular because I already use AngularJS for other projects, so I can integrate Angular objects and logic to add more/advanced functions to the form.

Why a custom AngularJS template rather than the built-in one?
Because the built-in one is very basic, don't function properly and not display the form.
So I decided to create a new custom template

For the last thing...I always use Our Umbraco (and probably it will be the next step), but I didn't find any util post about this question so I decided to try to contact you before writing on our umbraco

Adriano

**Comment by Nicholas-Westby** [comment]
@afabri73 I think the problem is the AngularJs version. With this version:

```html
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
```

There is an error. With this version:

```html
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
```

Things work fine. This page mentions the versions that have been tested: https://www.formulate.rocks/angularjs/render-form

Though, I recommend using the plain JavaScript version. It should be just as capable as the AngularJs version.
