### ISSUE TITLE
attachment on forms & copy forms

### ISSUE THREAD

**Issue by iangerdes** [rhythmagency/formulate#45]
hi 

is it possible to have a file attachment on the forms for a pdf/word file that would send onto the recipient emails?

also is it possible to copy/duplicate a form.

thanks

**Comment by Nicholas-Westby** [comment]
It's not possible to copy a form in the UI yet, but it is a planned feature: https://github.com/rhythmagency/formulate/issues/18

If you want to copy a form on the file system, you can find the JSON file and rename it and edit it so its GUID is unique and you'll have a copied form (note that the filename must be the same as the GUID).

I will leave this issue open so that I can add a new field type in the future that allows for an upload. Formulate is already extensible enough to allow for a developer to add that new field type themselves, but I will definitely make sure to add it to the core in the coming weeks/months (and if somebody reading this wants to submit a pull request, definitely leave a comment to let me know and I'll give you some pointers for how to implement).

**Comment by Nicholas-Westby** [comment]
FYI, there is now an upload file field type.
