### ISSUE TITLE
Sort created forms alphabetically

### ISSUE THREAD

**Issue by bjarnef** [rhythmagency/formulate#54]
I think the created forms should be sorted alphabetically by its node name.

![image](https://cloud.githubusercontent.com/assets/2919859/17537392/7974b01a-5e9c-11e6-9e48-35cf712c4779.png)

**Comment by Nicholas-Westby** [comment]
Makes sense to me. Isn't on my priority list, but I'd love a pull request. You could probably make the appropriate modifications around these lines (assuming each type of entity, not just forms, should be sorted alphabetically):

* https://github.com/rhythmagency/formulate/blob/af76b07d6e31755f32105ff502022060db31ae8e/src/formulate.app/Trees/FormulateTreeController.cs#L231
* https://github.com/rhythmagency/formulate/blob/af76b07d6e31755f32105ff502022060db31ae8e/src/formulate.app/Trees/FormulateTreeController.cs#L241
* https://github.com/rhythmagency/formulate/blob/af76b07d6e31755f32105ff502022060db31ae8e/src/formulate.app/Trees/FormulateTreeController.cs#L251
* https://github.com/rhythmagency/formulate/blob/af76b07d6e31755f32105ff502022060db31ae8e/src/formulate.app/Trees/FormulateTreeController.cs#L261
* https://github.com/rhythmagency/formulate/blob/af76b07d6e31755f32105ff502022060db31ae8e/src/formulate.app/Trees/FormulateTreeController.cs#L272

Let me know if you want some tips for making pull requests.

**Comment by axiom12** [comment]
Hi Nicholas,

I added the code in my local to alpha sort the children nodes (items and folders) but I'm not sure how to make a pull request. There's permission error. Can you give me a little assistance? I'm using the Github client for Windows.

Thanks and regards,
Jeremy

**Comment by Nicholas-Westby** [comment]
Hi Jeremy,

Sure, would be happy to have you contribute. If you are cloning directly from this repo, that won't work, as you will be unable to push directly to this repo (due to permissions). Instead, you should fork the repo so you have a copy (GitHub has a button to do this), then clone that repo to your local (using the Windows client), commit and push your change to that forked repo, then submit the pull request so I can review and merge in the change.

By the way, be sure to branch off of develop. There were a ton of changes done lately. And it would be best if you create a feature branch to do all your commits in (e.g., "feature/54-sort-forms").

Thanks! Let me know if you have further questions.

**Comment by Nicholas-Westby** [comment]
Closing this. Was completed in this PR: https://github.com/rhythmagency/formulate/pull/63
