### ISSUE TITLE
How to upgrade a Formulate installation?

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#75]
How to upgrade a Formulate installation?

**Comment by Nicholas-Westby** [comment]
Depends on how you installed it. If you installed it via the developer section's package manager, install the new version there.

If you installed it via NuGet, perform a NuGet upgrade.

After installing the new version, visit the website and wait a minute or two; Formulate runs some install/upgrade logic the first time it runs after an upgrade (e.g., it updates some config files).

Whichever approach you do, be sure to backup first (hopefully you are using source control). This is important because Formulate will overwrite certain files you may have customized, so you'll want to reincorporate your customizations.

**Comment by biapar** [comment]
Good. Thank you. I'll try.
